version: '3'
services:
  mysqldb:
    image: mysql/mysql-server:latest
    container_name: database
    restart: on-failure
    environment:
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3306:3306'
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      project:
        ipv4_address: 172.99.99.3
networks:
  project:
    external:
      name: int365
  int365:
    external: true